### ISSUE TITLE
Cannot select subnet

### ISSUE THREAD

**Issue by sjpb** [CycleCloudCommunity/cyclecloud_arm#9]
I've got an Azure Cyclecloud install done from the Azure Store (not using the button on the gitlab readme). It installed OK but then when creating a cluster (of any type) the GUI won't let me pick a subnet:
![no-subnet](https://user-images.githubusercontent.com/33413598/58967931-05ecae80-87ad-11e9-8462-ddbf2964b81e.PNG)

the dropdown has nothing populated and if I enter the subnet name manually it complains its not valid.

**Comment by jermth** [comment]
Hi, this doesn't really belong in this repo -- but try validating the service principal credentials you used for setting up CycleCloud -- this service principal needs to have sufficient privileges to list the VNETs in that region and subscription.
